name: Lint and prettify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Out
        uses: actions/checkout@v5

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Check virtual environment
        run: |
          poetry --version
          poetry check

      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: ~/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies
        run: poetry install --with dev --no-root --no-interaction

      - name: Run Script
        run: poetry run python -m scripts.main --is_in_gha=true

      - name: Lint
        run: make lint

      - name: per-commit hooks
        run: make pre-commit

      - name: Unit testing
        run: make unit-tests
