name: Lint and prettify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Out
        uses: actions/checkout@v7

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          # Install a specific version of uv.
          version: "0.12.1"

      - name: Check virtual environment
        run: uv version

      - name: Load cached venv
        uses: actions/cache@v5
        with:
          path: ~/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Run Script
        run: uv run python -m scripts.main --is_in_gha=true

      - name: Lint
        run: make lint

      - name: Format
        run: make format

      - name: per-commit hooks check
        run: make pre-commit

      - name: Unit testing
        run: make unit-tests
